name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-push-and-deploy:
    runs-on: ubuntu-latest

    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
      AZURE_WEBAPP_NAME: app-kontraktsportal-client-staging

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate image tag
        id: tag
        run: echo "tag=${{ github.sha }}" | cut -c1-11 >> $GITHUB_OUTPUT

      - name: Build and push image to registry
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.tag.outputs.tag }}
          file: ./Dockerfile

      - name: Deploy to Azure web app
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE_STAGING }}
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
